# Generated by Django 3.2.12 on 2022-03-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_rm_unused_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
